name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master main ]
  workflow_dispatch:
jobs:
  build:
    uses: minova-afis/aero.minova.github.workflows/.github/workflows/java-continuous-integration.yml@main
    secrets: inherit
