name: build

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  Build:
    uses: minova-afis/aero.minova.os.github.workflows/.github/workflows/pom-continuous-integration.yml@scr_java_21_lts
    secrets: inherit
