name: Release
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Version string of this release'
        required: true

jobs:
  Release:
    uses: minova-afis/aero.minova.os.github.workflows/.github/workflows/release-pom.yml@scr_java_21_lts
    with:
      release-version: ${{ inputs.release-version }}
    secrets: inherit
